name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest webdriver-manager
        
    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Start test server
      run: |
        cd dist
        python -m http.server 8000 &
        sleep 3  # Даем серверу время на запуск
        curl -s http://localhost:8000 || exit 1  # Проверяем доступность
    
    - name: Run tests
      run: |
        pytest tests/
